# Generated by Django 3.2 on 2023-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20230516_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(default='', max_length=25)),
                ('discount', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
