# Generated by Django 3.2 on 2023-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20230518_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('L', 'Laptops'), ('MF', 'MensFashion'), ('WF', 'WomensFashion'), ('G', 'Grocery'), ('H', 'HomeAppliances'), ('E', 'Electronics'), ('T', 'Toys'), ('Md', 'Medicine')], max_length=2),
        ),
    ]
