# Generated by Django 3.2 on 2023-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_1',
            field=models.CharField(default='Bank Offer 5% Unlimited Cashback on Axis Bank Credit', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_2',
            field=models.CharField(default='Special Price Get extra ₹3000 off (price inclusive of discount)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_3',
            field=models.CharField(default='No cost EMI ₹1,999/month. Standard EMI also available', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_4',
            field=models.CharField(default='Partner Offer ₹2000 ApnaMarket Gift Card on Every 1000th Transaction with a new Visa Debit/Credit Card', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
