# Generated by Django 3.2 on 2023-05-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Winter_Wears', 'Winter_Wears'), ('Blazers', 'Blazers'), ('Suits', 'Suits'), ('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Trackpants', 'Trackpants'), ('Shoes', 'Shoes'), ('Slippers', 'Slippers'), ('Wallets', 'Wallets'), ('Watches', 'Watches'), ('Sunglasses', 'Sunglasses'), ('Belts', 'Belts'), ('Jewellery', 'Jewellery'), ('Sarees', 'Sarees'), ('Tops', 'Tops'), ('Kurtas', 'Kurtas'), ('Purse', 'Purse'), ('Snacks_&_Beverages', 'Snacks_&_Beverages'), ('Packaged_Food', 'Packaged_Food'), ('Personal_&_Baby_Care', 'Personal_&_Baby_Care'), ('Household_Care', 'Household_Care'), ('Dairy_Products', 'Dairy_Products'), ('Home_&_Kitchen', 'Home_&_Kitchen'), ('Foodgrains', 'Foodgrains'), ('Home_Decor', 'Home_Decor'), ('Furniture', 'Furniture'), ('Lightings', 'Lightings'), ('Tools', 'Tools'), ('Audio', 'Audio'), ('Gaming', 'Gaming'), ('Laptop_Accessories', 'Laptop_Accessories'), ('Camera_Accessories', 'Camera_Accessories'), ('Television', 'Television'), ('Air_Conditioner', 'Air_Conditioner'), ('Refrigerator', 'Refrigerator'), ('Washing_Machine', 'Washing_Machine'), ('Others', 'Others'), ('Soft_Toys', 'Soft_Toys'), ('Remote_Control_Toys', 'Remote_Control_Toys'), ('Puzzles', 'Puzzles'), ('Board_Games', 'Board_Games'), ('Learning_Toys', 'Learning_Toys'), ('Baby_Toys', 'Baby_Toys')], default='Unknown', max_length=113),
        ),
    ]
