# Generated by Django 3.2 on 2023-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Home', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
