# Generated by Django 3.2 on 2023-07-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
