# Generated by Django 3.2 on 2023-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
