# Generated by Django 3.2 on 2023-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_orderplaced_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
