# Generated by Django 3.2 on 2023-11-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_alter_orderplaced_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
