# Generated by Django 3.2 on 2023-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_orderplaced_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='shipping',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
