# Generated by Django 3.2 on 2023-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='landmark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.CharField(max_length=500),
        ),
    ]
