# Generated by Django 3.2 on 2023-12-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_auto_20231230_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.CharField(max_length=200),
        ),
    ]
